"""
Django settings for ticket_server project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from celery.schedules import crontab
from datetime import timedelta

# https://sentry.io/bstr-ef/bstr-ef/getting-started/python-django/
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-%ai#-_+j2&m6bkfd7xu89m)cr!^k@_j*$!1#i$zqi!vuaqx71'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

##
# btr
#
DOMAIN = os.environ.get('BSTR_DOMAIN', 'local.myboostr.ru')


ALLOWED_HOSTS = [DOMAIN]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'drf_yasg',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django_celery_beat',
    'tickets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ticket_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'ticket_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ticket',
        'USER': 'ticket',
        'PASSWORD': '',
        'HOST': 'ticket_prod_db',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/api/static/'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'tickets.authentication.JWTAuthentication',
    ),
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S",
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

##
# files
#
MEDIA_URL = '/api/uploads/'
MEDIA_ROOT = '/tmp/'
##
# email
#
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_API_KEY = '6yzjd3mzq7kphfhzchr48fc8njxtwb1f19z4z63o'


# Time settings for journeys
LOCAL_TIMEZONE = 'Europe/Moscow'
UTC_DELTA = 3   # разница в часах между локальной зоной и UTC

# Celery config
CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'redis://redis:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'

CELERY_BEAT_SCHEDULE = {
    'task_every_day': {
        'task': 'tickets.tasks.task_every_day',
        'schedule': crontab(minute=0, hour=0),
    },
    'task_every_month': {
        'task': 'tickets.tasks.task_every_month',
        'schedule': crontab(0, 0, day_of_month='1'),
    },
    'task_every_year': {
        'task': 'tickets.tasks.task_every_year',
        'schedule': crontab(0, 0, day_of_month='1', month_of_year='1'),
    },
}

INSPECTOR_USERNAME = 'Inspector'
INSPECTOR_PASSWORD = 'DJsLSVXlBfye'

SIMPLE_JWT = {
    'SLIDING_TOKEN_LIFETIME': timedelta(weeks=1)
}

SENTRY_REPORTS = True

CSV_PATH = 'uploads/csv'
QR_PATH = '/tmp'
KEY_PATH = 'uploads/keys'
PRIVATE_KEY_FILENAME = 'private.pem'
PUBLIC_KEY_FILENAME = 'public.pem'


